fail_fast: true
repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.11.5
    hooks:
      - id: ruff-format
        name: "Ruff formatter"
        args: [--config=pyproject.toml]
        files: '^(docling_core|tests|docs/examples).*\.(py|ipynb)$'
      - id: ruff
        name: "Ruff linter"
        args: [--exit-non-zero-on-fix, --fix, --config=pyproject.toml]
        files: '^(docling_core|tests|docs/examples).*\.(py|ipynb)$'
  - repo: local
    hooks:
      - id: mypy
        name: MyPy
        entry: uv run --no-sync mypy docling_core test
        pass_filenames: false
        language: system
        files: '\.py$'
  - repo: local
    hooks:
      - id: flake8
        name: Flake8
        entry: uv run --no-sync flake8 docling_core
        pass_filenames: false
        language: system
        files: '\.py$'
  - repo: local
    hooks:
      - id: pytest
        name: Pytest
        entry: uv run --no-sync pytest --cov=docling_core --cov-report=xml test
        pass_filenames: false
        language: system
        files: '\.py$'
  - repo: local
    hooks:
      - id: docs
        name: Docs
        entry: uv run --no-sync python -m docling_core.utils.generate_docs docs
        pass_filenames: false
        language: system
        files: '\.py$'
  - repo: https://github.com/astral-sh/uv-pre-commit
    rev: 0.7.8
    hooks:
      - id: uv-lock
